name = "asset-dashboard-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 17 * * *"]  # 매일 UTC 17:00 = KST 02:00 스냅샷

[[kv_namespaces]]
binding = "KV"
id = "c6cd88ef715c479ca351563f21421e6e"
