name = "asset-dashboard-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 7 * * *"]  # 매일 KST 16:00 (UTC 07:00) - 장 마감 30분 후

[[kv_namespaces]]
binding = "KV"
id = "c6cd88ef715c479ca351563f21421e6e"
